name: pmsn20232
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  youtube_player_flutter: ^8.1.2
  filter_list: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  path_provider: ^2.1.1
  day_night_switcher: ^0.2.0+1
  sqflite: ^2.3.0
  http: ^0.13.5
  syncfusion_flutter_calendar: ^23.1.36
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  flutter_local_notifications: ^16.1.0
  device_info_plus: ^9.1.0
  flutter_timezone: ^1.0.8
  image: ^4.1.3
  timezone: ^0.9.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/